# Generated by Django 4.1.2 on 2022-10-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_listings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bids',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='dsecription',
            new_name='description',
        ),
    ]
